### ISSUE TITLE
Feature Request: add some documentation

### ISSUE THREAD

**Issue by aslmx** [jplitza/nina_xmpp#7]
Hi,
came across this project through the monthly XSF xmpp newsletter.
I tried your public instance and it seems very useful to me.
I'd like to run it for my self though, but can't get it working.

i ran `python3 setup.py build` and i'm now able to run

`nina_xmpp config.yml`  
(i added some credentials into the config.sample.yml and renamed it to config.yml)

But it won't like the database.

`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
`

 I'm sure it is because I'm missing a crucial step.

So I'd like to friendly request a minimal "how to get it running guide"

Or is it somewhere and I'm too blind to find it? ;)

thanks!

**Comment by jplitza** [comment]
Hm, off the top of my hat, I would have expected those steps to be enough. But I will check if the database somehow has to be pre-created.

Are you sure the directory of the database file exists an is writeable by your user?

**Comment by aslmx** [comment]
> Are you sure the directory of the database file exists an is writeable by your user?

well, after those steps there is a database.db with 0 bytes in size. I have no idea when exactly it was created and if that is expected to be correct.

I cloned the repo to 
`~/tools/nina_xmpp`

config.yml contains 
`database: sqlite:///database.db `
(i also tried with absolute path to no avail)

and am running from that folder
`~/tools/nina_xmpp[master]:$ nina_xmpp config.yml`

full output is

```

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 622, in __connect
    pool.dispatch.connect.for_modify(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/event/attr.py", line 329, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/event/attr.py", line 343, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/nina_xmpp-4-py3.8.egg/nina_xmpp/db.py", line 14, in _load_spatialite
    dbapi_conn.load_extension('mod_spatialite')
sqlite3.OperationalError: mod_spatialite.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/nina_xmpp", line 11, in <module>
    load_entry_point('nina-xmpp==4', 'console_scripts', 'nina_xmpp')()
  File "/usr/local/lib/python3.8/dist-packages/nina_xmpp-4-py3.8.egg/nina_xmpp/__main__.py", line 19, in main
    main = NinaXMPP(config)
  File "/usr/local/lib/python3.8/dist-packages/nina_xmpp-4-py3.8.egg/nina_xmpp/__init__.py", line 31, in __init__
    self.db = init_db(config['database'])
  File "/usr/local/lib/python3.8/dist-packages/nina_xmpp-4-py3.8.egg/nina_xmpp/db.py", line 47, in initialize
    with engine.connect() as conn:
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3215, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2069, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 622, in __connect
    pool.dispatch.connect.for_modify(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/event/attr.py", line 329, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/event/attr.py", line 343, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/nina_xmpp-4-py3.8.egg/nina_xmpp/db.py", line 14, in _load_spatialite
    dbapi_conn.load_extension('mod_spatialite')
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) mod_spatialite.so: cannot open shared object file: No such file or directory
(Background on this error at: https://sqlalche.me/e/14/e3q8)

```

thanks!

**Comment by jplitza** [comment]
That's a different message than in your first post.

You're missing mod_spatiallite. Yes, I should document that you need that and how to install it.

**Comment by aslmx** [comment]
> That's a different message than in your first post.

sorry, that must have slipped my attention.

> You're missing mod_spatiallite. Yes, I should document that you need that and how to install it.

Yeah thanks, that was it.

a short search and 

`sudo apt-get install libsqlite3-mod-spatialite`

later, nina-xmpp is running :-)

Thanks a lot!

I put my notes into a PR, if you like

https://github.com/jplitza/nina_xmpp/pull/8
